apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: preservation-identity-test
spec:
  environments:
  - name: dev

  components:
  # ---------
  # Backend
  #---------- 
  - name: backend
    image: procosys.azurecr.io/preservation/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets:
    - CONNECTIONSTRINGS__APPCONFIG
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 67b2f053-30bf-4ffc-9206-ef57f631efcb
      imageTagName: latest
      variables:
        ASPNETCORE_ENVIRONMENT: 'Development'
        UseAzureAppConfiguration: 'true'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: false
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '250m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'

  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
