apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: procosys-preservation-api
spec:
    environments:
        - name: dev
          build:
              from: pbi/104952_Move_Preservation_API_to_Radix
#        - name: test
#        - name: prod
    components:
        - name: backend
          identity:
                azure:
                    clientId: cb7afa3f-d2ff-401b-83b6-f02cce85ce30
          image: procosys.azurecr.io/preservation/api:{imageTagName}
    
          ports:
              - name: http
                port: 5000
          publicPort: http 
          secrets:
              - CONNECTIONSTRINGS__APPCONFIG
              - AZURE_CLIENT_SECRET
          environmentConfig:
              - environment: dev
                imageTagName: latest
                variables:
                    ASPNETCORE_ENVIRONMENT: 'Development'
                    UseAzureAppConfiguration: 'true'
                monitoring: true
                resources:
                    requests:
                        memory: '128Mi'
                        cpu: '100m'
                    limits:
                        memory: '256Mi'
                        cpu: '250m'
    privateImageHubs:
      procosys.azurecr.io:
        username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
        email: arbje@equinor.com

 #             - environment: test
 #               variables:
 #                   SEARCH_ENVIRONMENT_NAME: 'TEST'
 #               replicas: 2
 #               resources:
 #                   requests:
 #                       memory: '128Mi'
 #                       cpu: '100m'
 #                   limits:
 #                       memory: '256Mi'
 #                       cpu: '250m'
 #             - environment: prod
 #               variables:
 #                   SEARCH_ENVIRONMENT_NAME: 'PROD'
 #               replicas: 2
 #               monitoring: true
 #               resources:
 #                   requests:
 #                       memory: '128Mi'
 #                       cpu: '100m'
 #                   limits:
 #                       memory: '256Mi'
 #                       cpu: '250m'
