apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-preservation-api
spec:
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  # ---------
  # Backend
  #---------- 
  - name: backend
    image: procosys.azurecr.io/preservation/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets:
    - CONNECTIONSTRINGS__APPCONFIG
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 67b2f053-30bf-4ffc-9206-ef57f631efcb
      imageTagName: latest
      variables:
        ASPNETCORE_ENVIRONMENT: 'Development'
        UseAzureAppConfiguration: 'true'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: false
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '2048Mi'
          cpu: '1000m'
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: f23bcde6-d6a4-42d5-94fa-96b184968cf7
      imageTagName: latest
      variables:
        ASPNETCORE_ENVIRONMENT: 'Test'
        UseAzureAppConfiguration: 'true'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: false
      replicas: 2
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '2048Mi'
          cpu: '1000m'
    # Prod environment
    - environment: prod
      identity:
        azure:
          clientId: 1eb50c54-e897-4216-93d0-6ca86b0cf681
      imageTagName: latest
      variables:
        ASPNETCORE_ENVIRONMENT: 'Prod'
        UseAzureAppConfiguration: 'true'
        LEADERELECTOR_SERVICE: http://leader-electorTULL:3003
      monitoring: false
      replicas: 2
      resources:
        requests:
          memory: '128Mi'
          cpu: '1000m'
        limits:
          memory: '2048Mi'
          cpu: '1000m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
    # Test environment
    - environment: test
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: true
    # Prod environment
    - environment: prod
      imageTagName: latest
      variables:
         LEASE_TIME: 5
      monitoring: false
  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
