trigger:
  branches:
    include:
      - build-test


resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-preservation-infra
    endpoint: Preservation - Frontend


variables:
 - template: templates/globalvariables.yml@templates

stages:
- stage: Dev
  displayName: 'Build and publish to Dev'
  variables:
    envName: 'dev'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'

  jobs:
  - template: /pipelines/build-template.yml
    parameters:
      deploymentName: 'Deploy_API'
      dependsOn:
      serviceConnection: ${{ variables.serviceConnection }}
      env: 'pcs-${{ variables.envName }}'