trigger:
  branches:
    include:
      - build-test


resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-preservation-infra
    endpoint: Preservation - Frontend


variables:
 - template: templates/globalvariables.yml@templates
 - name: webAppName
   value: 'pcs-pres-$(envName)-api'

stages:
- stage: Dev
  displayName: 'Build and publish to Dev'
  variables:
    envName: 'dev'
    envRg: 'pcs-preservation-dev-rg'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServiceName: $(nonProdappServicePlanName)

  jobs:
  - template: /pipelines/build-template.yml
    parameters:
      deploymentName: 'Deploy_API'
      dependsOn:
      serviceConnection: ${{ variables.serviceConnection }}
      env: 'pcs-${{ variables.envName }}'

  - template: /templates/pipelines/webappcontainer.yml@templates
    parameters:
      deploymentName: 'Update_Web_App'
      dependsOn: 'Deploy_API'
      serviceConnection: ${{ variables.serviceConnection }}
      env: 'pcs-${{ variables.envName }}'
      webAppName: '${{ variables.webAppName }}'
      appServicePlanName: $(appServiceName)