trigger:
  branches:
    include:
      - build-test

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-templates
    endpoint: 'Preservation - Frontend'

# Global variables for the pipeline
variables:
 - template: variables/preservation-variables.yml@templates
 - template: variables/procosys-global-variables.yml@templates

 - name: apiWebAppName
   value: '$(globalPrefix)-$(shortAppName)-$(envName)-api'

#  - name: projectName
#    value: 'apitestproject_new'

stages:
# Dev stage
- stage: Dev
  displayName: 'Dev'
  variables:
    envName: 'dev'
    envRg: '${{ variables.envRgName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServicePlan: '${{ variables.nonProdappServicePlanName }}'
    containerRegistry: '${{ variables.containerRegistryName }}' 
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'
    dockerfilePath: '/src/Equinor.Procosys.Preservation.WebApi/Dockerfile'
    repositoryName: 'api'

  jobs:
  - template: /pipelines/dockerbuild.yml@templates
    parameters:
        deploymentName: 'docker_build_push'
        dependsOn: ''
        envName: 'pcs-${{ variables.envName }}'
        dockerfilePath: ${{ variables.dockerfilePath }}
        repository: ${{ variables.repositoryName }}
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnectionName)
        tag: ''

# Test stage
- stage: Test
  displayName: 'Test'
  variables:
    envName: 'test'
    envRg: '${{ variables.envRgName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServicePlan: '${{ variables.nonProdappServicePlanName }}'
    containerRegistry: '${{ variables.containerRegistryName }}' 
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'
    dockerfilePath: '/src/Equinor.Procosys.Preservation.WebApi/Dockerfile'
    repositoryName: 'api'


  jobs:
  - template: /pipelines/dockerbuild.yml@templates
    parameters:
        deploymentName: 'docker_build_push'
        dependsOn: ''
        envName: 'pcs-${{ variables.envName }}'
        dockerfilePath: ${{ variables.dockerfilePath }}
        repository: ${{ variables.repositoryName }}
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnectionName)
        tag: '${{ variables.envName }}-latest'

