trigger:
  branches:
    include:
      - build-test


resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-preservation-infra
    endpoint: Preservation - Frontend

# Global variables for the pipeline
variables:
 - template: templates/preservation-variables.yml@templates

 - name: webAppName
   value: 'pcs-pres-$(envName)-api'

 - name: projectName
   value: 'apitestproject'

stages:
- stage: Dev
  displayName: 'Build and publish to Dev'
  variables:
    envName: 'dev'
    envRg: 'pcs-preservation-dev-rg'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServicePlan: 'pcs-pres-non-prod-app-service-plan'

  jobs:
  - template: /pipelines/build-template.yml
    parameters:
      deploymentName: 'Build_and_push_docker_image'
      dependsOn:
      serviceConnection: ${{ variables.serviceConnection }}
      env: 'pcs-${{ variables.envName }}'

  - template: /templates/pipelines/webappcontainer.yml@templates
    parameters:
      deploymentName: 'Update_Web_App'
      dependsOn: 'Build_and_push_docker_image'
      serviceConnection: ${{ variables.serviceConnection }}
      env: 'pcs-${{ variables.envName }}'
      webAppName: '${{ variables.webAppName }}'