parameters:
  deploymentName: ''
  dependsOn: ''
  serviceConnection: ''
  env: ''

jobs:
- deployment: ${{ parameters.deploymentName }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: '${{ parameters.deploymentName }}'
  pool: 
    vmImage: '$(vmImageName)'
  environment: '${{ parameters.env }}'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: DockerCompose@0
          displayName: Build
          inputs:
            action: Build services
            azureSubscriptionEndpoint: '${{ parameters.serviceConnection }}'
            azureContainerRegistry: '$(containerRegistry)'
            dockerComposeFile: '$(Build.SourcesDirectory)$(composeFilePath)'
            additionalImageTags: $(Build.BuildId)
            projectName: 'apitestproject'

        - task: DockerCompose@0
          displayName: Push services
          inputs:
            action: Push services
            azureSubscriptionEndpoint: '${{ parameters.serviceConnection }}'
            azureContainerRegistry: 'pcspreservation.azurecr.io'
            dockerComposeFile: '$(Build.SourcesDirectory)$(composeFilePath)'
            projectName: $(Build.Repository.Name)
            qualifyImageNames: true
            additionalImageTags: $(Build.BuildId)