parameters:
  dependsOn: ''
  deploymentName: ''
  serviceConnection: ''
  envGroup: ''
  connectionString: ''
  kvName: ''
  kvRgName: ''
  serverName: ''
  databaseName: ''

jobs:
  - deployment: '${{ parameters.deploymentName }}'
    dependsOn: '${{ parameters.dependsOn }}'
    displayName: '${{ parameters.deploymentName }}'
    environment: '${{ parameters.envGroup }}'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: 'Checkout source code'

            - task: AzurePowerShell@4
              displayName: 'Get KeyVault Secret'
              inputs:
                azurePowerShellVersion: LatestVersion
                azureSubscription: '${{ parameters.serviceConnection }}'
                ScriptType: InlineScript
                Inline: |
                    # Variables
                    $kvName = "${{ parameters.kvName }}"
                    $kvSecret = "pcssqladmin-test"
                    $rgName = "${{ parameters.kvRgName }}"
                        
                    # Temporarily disable firewall for Key Vault
                    Update-AzKeyVaultNetworkRuleSet -VaultName $kvName -ResourceGroupName $rgName -DefaultAction Allow
                    $secretName = (Get-AzKeyVaultSecret -VaultName $kvName -Name $kvSecret).SecretValueText
                        
                    # Create reusable variable for env task with $(kvoSecret)
                    Write-Host "##vso[task.setvariable variable=kvoSecret;issecret=true;]$secretName"
                        
                    # Enable firewall for Key Vault
                    Update-AzKeyVaultNetworkRuleSet -VaultName $kvName -ResourceGroupName $rgName -DefaultAction Deny

            # Download Pipeline Artifact
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: 'SQLMigration'
                path: $(System.DefaultWorkingDirectory)

            # Deploy Script
            - task: SqlAzureDacpacDeployment@1
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                AuthenticationType: 'server'
                ServerName: '${{ parameters.serverName }}'
                DatabaseName: '${{ parameters.databaseName }}'
                SqlUsername: 'pcssqladmin'
                SqlPassword: '$(kvoSecret)'
                deployType: 'SqlTask'
                SqlFile: '$(System.DefaultWorkingDirectory)/migration.sql'
                IpDetectionMethod: 'AutoDetect'