name: Test Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: src/
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Configure NuGet source
        working-directory: src/
        run: |
          dotnet nuget update source ProCoSysOfficial \
              --username statoildeveloper \
              --password ${{ secrets.AZURE_ARTIFACTS_PAT }} \
              --store-password-in-clear-text
      - run: ls -l
      - name: Run tests
        run: dotnet test src/Equinor.ProCoSys.Preservation.sln