name: Test Runner

on: [push]

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - run: dotnet test