name: Test Runner

on: [push]

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - name: Configure NuGet source
        run: |
          dotnet nuget add source --name ProCoSysOfficial \
              --username statoildeveloper \
              --password ${{ secrets.AZURE_ARTIFACTS_PAT }} \
              --store-password-in-clear-text \
              https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json
      - name: Run tests
        run: dotnet test