name: Test Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Configure NuGet source
        run: |
          cd src/
          dotnet nuget update source ProCoSysOfficial \
              --username statoildeveloper \
              --password ${{ secrets.AZURE_ARTIFACTS_PAT }} \
              --store-password-in-clear-text
      - name: Run tests
        run: |
          cd src/
          dotnet test